{
    "CGI": null,
    "GG": [
    {
        "BID": 1223,
        "CC": false,
        "CDE": false,
        "CID": "14774",
        "CM": false,
        "GM": false,
        "GNO": null,
        "GT": 1,
        "IC": "20-087-8419",
        "ID": 51320,
        "ImageItemCode": "20-087-8419",
        "ImageNameFull": "19122.jpg",
        "IsLeTian": false,
        "IsLuxuxy": false,
        "IsStockout": false,
        "LK": "http://item.yintai.ts2/20-087-8419.html",
        "MP": 396,
        "MZMP": {
            "MainItemModels": [
                {
                    "BID": 0,
                    "CC": true,
                    "CDE": true,
                    "CID": "14233",
                    "CM": true,
                    "CostPoints": 0,
                    "DC": 4.8,
                    "ET": "2016/5/31 0:00:00",
                    "GM": false,
                    "GNO": null,
                    "IC": "20-355-3673",
                    "ID": 51320,
                    "ImageItemCode": "20-355-3672",
                    "ImageNameFull": "727.jpg",
                    "IsNoStock": false,
                    "LB": {
                        "IsCP": false,
                        "IsL": false,
                        "IsLT": false,
                        "IsPS": false,
                        "IsS": false,
                        "NotRma": false,
                        "PB": null,
                        "PSM": "",
                        "PT": 3
                    },
                    "LK": "http://item.yintai.ts2/20-355-3673.html",
                    "MP": 299,
                    "MZMP": null,
                    "MaP": [
                        {
                            "PpN": "尺码",
                            "PpV": "38"
                        },
                        {
                            "PpN": "颜色",
                            "PpV": "月光蓝"
                        }
                    ],
                    "NM": "ASOBIO商务通勤翻领修身长袖衬衫3322322817,月光蓝,38",
                    "PP": null,
                    "PST": "B",
                    "PT": 3,
                    "PointRate": 0,
                    "Points": 290,
                    "Qty": 2,
                    "SRC": "http://p10.ytrss.com/product/20/355/3672/normalimage/727.jpg",
                    "ST": "2016/3/9 17:04:27",
                    "TY": 0,
                    "Tips": null,
                    "Tit": "ASOBIO商务通勤翻领修身长袖衬衫3322322817,月光蓝,38",
                    "WNum": null,
                    "YTP": 145
                }
            ],
            "PromotionName": "官网0元赠-特卖-勿动"
        },
        "MaP": [
            {
                "PpN": "容量",
                "PpV": "120ML"
            }
        ],
        "NM": "Lumi纤体系列紧致小腿霜120ml(赠品)",
        "NotRma": false,
        "PointRate": 0,
        "Points": 0,
        "ProductSaleType": null,
        "PromotionName": "官网0元赠-特卖-勿动",
        "Qty": 1,
        "SRC": "http://p10.ytrss.com/product/20/087/8419/normalimage/19122.jpg",
        "Tit": "Lumi纤体系列紧致小腿霜120ml(赠品)",
        "WarehouseNumber": null,
        "YTP": 0
    }
],
    "GM": [],
    "HasGift": false,
    "IM": {
    "BID": 0,
        "CC": true,
        "CDE": true,
        "CID": "13659",
        "CM": true,
        "CostPoints": 0,
        "DC": 4.7,
        "ET": "2016/5/31 0:00:00",
        "GM": false,
        "GNO": null,
        "IC": "06-007-0532",
        "ID": 0,
        "ImageItemCode": "06-007-0516",
        "ImageNameFull": "36600.jpg",
        "IsNoStock": false,
        "LB": {
        "IsCP": false,
            "IsL": false,
            "IsLT": false,
            "IsPS": false,
            "IsS": false,
            "NotRma": false,
            "PB": null,
            "PSM": "",
            "PT": 3
    },
    "LK": "http://item.yintai.ts2/06-007-0532.html",
        "MP": 399,
        "MZMP": null,
        "MaP": [],
        "NM": "ASOBIO阿索比亚鞋4102811189099",
        "PP": null,
        "PST": "",
        "PT": 0,
        "PointRate": 0,
        "Points": 188,
        "Qty": 1,
        "SRC": "http://p10.ytrss.com/product/06/007/0516/normalimage/36600.jpg",
        "ST": "2016/3/9 17:04:27",
        "TY": 0,
        "Tips": null,
        "Tit": "ASOBIO阿索比亚鞋4102811189099",
        "WNum": null,
        "YTP": 188
},
    "IsSucceed": false,
    "PM": {
    "BA": 0,
        "DU": null,
        "GP": 0,
        "GQ": 0,
        "Guid": null,
        "IC": null,
        "ICJ": null,
        "ID": 0,
        "IMR": false,
        "NM": null,
        "PA": 0,
        "PC": 0,
        "PP": 0,
        "PT": 0,
        "RN": null,
        "RNum": null,
        "RU": false,
        "TP": null
},
    "PMS": null,
    "TotalModel": {
    "Am": 6080,
        "CU": 0,
        "MU": 0,
        "PT": 7134,
        "Qty": 18,
        "RA": 885.6,
        "SF": {
        "ASF": 0,
            "IsESF": true,
            "RFN": 199,
            "SSF": 15
    },
    "TPT": 0,
        "YTA": 5194.4
}
}